layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:2019/:May/:09/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: YouTube
    web_url: https://youtube.com
    image_url: https://www.youtube.com/yt/about/media/images/brand-resources/logos/YouTube-logo-full_color_light.svg

  - name: Twitch
    web_url: https://www.twitch.tv/
    image_url: https://www.twitch.tv/p/assets/uploads/glitch_474x356.png

  - name: Netflix
    web_url: https://www.netflix.com/
    image_url: https://media.netflix.com/dist/img/meta-image-netflix-symbol-black.png